"""添加学习工具和模式字段

Revision ID: 1680ca1ed645
Revises: c1d2e3f4g5h6
Create Date: 2026-01-01 05:21:04.792192

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1680ca1ed645"
down_revision: Union[str, Sequence[str], None] = "c1d2e3f4g5h6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 只添加新字段，不删除索引（索引在数据库中有效，不应被移除）
    op.add_column(
        "learn_sessions",
        sa.Column("learning_mode", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "learn_sessions", sa.Column("current_tool", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "learn_sessions",
        sa.Column("tool_plan", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚时只删除新增的字段
    op.drop_column("learn_sessions", "tool_plan")
    op.drop_column("learn_sessions", "current_tool")
    op.drop_column("learn_sessions", "learning_mode")
    # ### end Alembic commands ###
