"""添加 learn_messages.tool 字段

Revision ID: c9cb822b00d0
Revises: 1680ca1ed645
Create Date: 2026-01-01 05:36:15.061996

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9cb822b00d0"
down_revision: Union[str, Sequence[str], None] = "1680ca1ed645"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 只添加新字段，不删除索引
    op.add_column(
        "learn_messages", sa.Column("tool", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚时只删除新字段
    op.drop_column("learn_messages", "tool")
    # ### end Alembic commands ###
