"""add step_history analytics_events and solve_session_fields

Revision ID: db20586a27bf
Revises: 3b3f0b3a2c1d
Create Date: 2025-12-22 08:55:57.407048

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db20586a27bf"
down_revision: Union[str, Sequence[str], None] = "3b3f0b3a2c1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_webhook_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processed_webhook_events_event_id"),
        "processed_webhook_events",
        ["event_id"],
        unique=True,
    )
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["solve_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "step_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("step", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["solve_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens"
    )
    op.add_column(
        "solve_sessions", sa.Column("locale", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "solve_sessions", sa.Column("first_step_action", sa.Text(), nullable=True)
    )
    op.add_column(
        "solve_sessions", sa.Column("reminder_time", sa.DateTime(), nullable=True)
    )
    op.drop_index(op.f("ix_solve_sessions_user_id"), table_name="solve_sessions")
    op.drop_index(op.f("ix_solve_sessions_user_status"), table_name="solve_sessions")
    op.add_column(
        "subscriptions", sa.Column("cancel_at_period_end", sa.Boolean(), nullable=True)
    )
    op.create_index(op.f("ix_usage_user_id"), "usage", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uq_usage_user_period", "usage", ["user_id", "period_start"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_usage_user_period", "usage", type_="unique")
    op.drop_index(op.f("ix_usage_user_id"), table_name="usage")
    op.drop_column("subscriptions", "cancel_at_period_end")
    op.create_index(
        op.f("ix_solve_sessions_user_status"),
        "solve_sessions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_solve_sessions_user_id"), "solve_sessions", ["user_id"], unique=False
    )
    op.drop_column("solve_sessions", "reminder_time")
    op.drop_column("solve_sessions", "first_step_action")
    op.drop_column("solve_sessions", "locale")
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=False,
    )
    op.drop_table("step_history")
    op.drop_table("analytics_events")
    op.drop_index(
        op.f("ix_processed_webhook_events_event_id"),
        table_name="processed_webhook_events",
    )
    op.drop_table("processed_webhook_events")
    # ### end Alembic commands ###
