name: ✨ Beta Feature Request
description: Suggest a new feature or improvement for Clarity
title: "[Feature Request] "
labels: ["beta", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Clarity better? We'd love to hear it! Please describe your feature request below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature or improvement would you like to see?
      placeholder: |
        Example:
        I'd like to be able to export my session history as a PDF or text file.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: User Scenario
      description: When and why would you use this feature? What problem does it solve?
      placeholder: |
        Example:
        After completing a Solve session, I want to review my decision later or share it with a friend. Currently, I have to screenshot everything manually.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How Important Is This to You?
      description: How much would this feature improve your experience?
      options:
        - Must-Have (I won't use the app without it)
        - Nice-to-Have (Would be very helpful)
        - Low Priority (It's just an idea)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Current Workaround
      description: Is there a way you currently work around this limitation? (Optional)
      placeholder: |
        Example:
        I take screenshots of each step manually and save them to my phone.
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Similar Features in Other Apps
      description: Have you seen this feature in other apps? If so, which ones? (Optional)
      placeholder: |
        Example:
        Notion allows exporting pages as PDF or Markdown. Something like that would be great.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details, mockups, or ideas? (Optional)
      placeholder: Any other thoughts?
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Info (Optional)
      description: Email or preferred contact method if we can follow up
      placeholder: "e.g., your-email@example.com or WeChat ID"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Privacy Note**: This feature request will be visible to the Clarity team. Please do not include sensitive personal information.

        **Need Help?** Check our [Beta Tester Guide](https://github.com/412984588/clarity/blob/main/docs/release/free-beta-tester-guide.md) or [Issue Intake Guide](https://github.com/412984588/clarity/blob/main/docs/release/beta-issue-intake.md).
