#!/bin/sh

# 获取项目根目录
ROOT_DIR=$(git rev-parse --show-toplevel)

# 后端检查
cd "$ROOT_DIR/solacore-api" && poetry run pre-commit run --all-files || exit 1

# Web 前端检查（可选，lint-staged 可能失败如果没有改动）
cd "$ROOT_DIR/solacore-web" && npx lint-staged || true

# Mobile 前端检查
cd "$ROOT_DIR/solacore-mobile" && npx lint-staged || true
